name: whatsapp_clone
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  line_icons: ^2.0.1
  flutter_svg: ^1.1.3
  animate_do: ^2.1.0
  dio: ^4.0.6
  grouped_list: ^5.1.2
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/bg_chat.jpg

